#!/bin/env python

#### configuration file ####
configfile: "config/config.yaml"

include: "rules/common.smk"

wildcard_constraints:
    oqs_name="|".join(config["oqs"].keys()),

rule all:
    input:
        lambda w: allInput(),

# Downloading reference genome and generating related files
include: "rules/prepare_genome.smk"

# Generate G4 regions with different methodologies
include: "rules/prepare_oqs.smk"  # Prepare OQS regions
include: "rules/gc_rich_bg.smk"  # Prepare GC-rich genome background
include: "rules/g4p_chip_seq.smk"  # g4chip peaks from FASTQ
include: "rules/g4p_cut_tag.smk"  # g4cuttag peaks from FASTQ
include: "rules/g4chip_g4cuttag_merge.smk"  # Merge g4chip and g4cuttag intervals
include: "rules/rnaseq.smk"  # RNA-seq quantification and DESeq2 time-series
include: "rules/g4_tss.smk"  # G4-TSS transcription analysis (Tasks 1-8)
