jobs: 100

# Configure for Snakemake >= 8.0
executor: "cluster-generic"
cluster-generic-submit-cmd: "sbatch -A {resources.account} -p {resources.partition} -J {rule}.job --qos {resources.qos} --cpus-per-task={threads} --mem={resources.mem_mb} {resources.slurm_extra} -e logs/cluster/{rule}_%A.err --output=/dev/null"
software-deployment-method: "conda"

printshellcmds: True
keep-going: True
rerun-incomplete: True
rerun-triggers: "mtime"
# rerun-triggers: "input"

#set-resources: [
#  meme_chip:ntasks=8, 
#  ]


# default-resources: [account='investor', partition='mid_investor', qos="mid_investor"]
# default-resources: [account='users', partition='long_mdbf', qos="long_mdbf"] # sakura
# default-resources: [account='mdbf', partition='mid_mdbf', qos="mid_mdbf"]
default-resources: [account='adelab', partition='genomics', qos="adelab", slurm_extra='', mem_mb=8000]
